# Generated by Django 4.2 on 2023-05-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_service_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
