# Generated by Django 4.2 on 2023-05-09 15:19

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_service_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[128, 160],
                upload_to="services/",
            ),
        ),
    ]
