# Generated by Django 4.2 on 2023-05-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_service_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(upload_to="services/"),
        ),
    ]
