# Generated by Django 4.2 on 2023-05-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="about",
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
