# Generated by Django 4.2 on 2023-05-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_artist_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="image",
            field=models.ImageField(null=True, upload_to="artist/"),
        ),
    ]
